hash-format = "sha256"

[[files]]
file = "config/craftpresence.properties"
hash = "ca6b6342dfa456d955bc1b399f0fa74332d6a88ead6bf77a615115c536a55cc9"

[[files]]
file = "config/xaerominimap.txt"
hash = "a0afc6c2a79d0b46b97a4175a81faec5a8bef25aa087e455d8790505ed3408f0"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "cf2dcdca67076c7b59573140082f166da0c260cf932120eee956632f2e6870f6"

[[files]]
file = "mods/AdvancementPlaques-1.18.2-fabric-1.4.5.jar"
hash = "70fba689b45512a0ad8f225434e9000d80ebdf20f3a27224344a55f768df31b8"

[[files]]
file = "mods/Bookshelf-Fabric-1.18.2-13.2.34.jar"
hash = "91e2f5a6f4025a12b7168518fa854907fbeb135ba4a0298a1430a26218109dc8"

[[files]]
file = "mods/Chunky-1.2.164.jar"
hash = "8ec6841b7afc28eee5f2268868f78379272af6112561d9f9fa66bd4347ac3954"

[[files]]
file = "mods/CosmeticArmor-1.18.2-1.3.1.jar"
hash = "3fdd694b79e3517fa39d1341ca9ba2ba1c9a83be7f3e9756ecf2427424083ed1"

[[files]]
file = "mods/CraftPresence-Fabric-1.18.2-Release-1.8.8.jar"
hash = "c64597656e04b9d4667013394330e95c1736c614c316100a391b2a4c83b0b004"

[[files]]
file = "mods/DarkUtilities-Fabric-1.18.2-10.0.5.jar"
hash = "b42fda6db18c0f45678eecc99d084c26c1afa28777091c242bf6c8643d1898af"

[[files]]
file = "mods/ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric.jar"
hash = "60e2761d249dacf7cc6235c38087427166039b4ae26116e8e65b3b14ac3c44dc"

[[files]]
file = "mods/Iceberg-1.18.2-fabric-1.0.38.jar"
hash = "70096b8c2c6849ec975c2d8d7ac874a6d6766761255c1a9c4a1d9c100e28fc26"

[[files]]
file = "mods/MinecraftCapes Fabric 1.18.2-12.0.2.jar"
hash = "cb517788d7fe58e49b0e289161dc2c11a028901f0ebf6c6c0d9b9907019379cc"

[[files]]
file = "mods/Origins-1.18.2-1.4.1.jar"
hash = "e6792ae6b3c04cbc13d77428ef506d83eae452fd14c4e220a1e09ee53c33900c"

[[files]]
file = "mods/Pehkui-3.3.3+1.14.4-1.19.1.jar"
hash = "14b307479b4c059200fe0b2defba3e5526861486a020b727a8ef1383ca625bd7"

[[files]]
file = "mods/PigPen-Fabric-1.18.2-8.0.1.jar"
hash = "a32d435e00097f303b2f57c0a590c19971430c6c6436c873b3f8cee8cd140a1a"

[[files]]
file = "mods/PresenceFootsteps-1.5.1.jar"
hash = "b8ef1f8f19b82f02004a4c45dc91b20adad29461a641137c9d5e0c09e1014291"

[[files]]
file = "mods/Runelic-Fabric-1.18.2-11.0.1.jar"
hash = "7ac8e32eb160d67a20adc93f23c80b4e595f1f620c5f653eeb238ff72b643984"

[[files]]
file = "mods/Tips-Fabric-1.18.2-5.0.3.jar"
hash = "5ea3ac5b52db468d5551bf86352706d2554051e9afd3d8ac5dc3e90882338f97"

[[files]]
file = "mods/XaerosWorldMap_1.24.0_Fabric_1.18.2.jar"
hash = "c419eadc19521d8472b5e50a5165e78f380b3ae96ce2a277168d3bba98e29e7f"

[[files]]
file = "mods/Xaeros_Minimap_22.10.0_Fabric_1.18.2.jar"
hash = "65faf917ead9828147166f63f2cf5c1ea56195f07f4d01de7addf0a3bbdbdf6d"

[[files]]
file = "mods/appliedenergistics2-11.1.4.jar"
hash = "13be7bb1da05dcf1a5f39562f0e410cc527f8306d048bf3a1fd2bc26c3a5065a"

[[files]]
file = "mods/arcanus-1.29.jar"
hash = "7347b225b129e0645b10249001d7fa71816db7a6ad9fcc1a27a6f6e5746a74eb"

[[files]]
file = "mods/badpackets-fabric-0.1.2.jar"
hash = "205b163eab823e77a72624e8cf855563f8cc0e45ed8f8ff45331f397e0d48954"

[[files]]
file = "mods/campanion-3.0.4.jar"
hash = "bf81b31462e5e02183eff95f3e6a5719f35baa4e7ab04268d51ede57555125a7"

[[files]]
file = "mods/can-i-mine-this-block-1.2.0.jar"
hash = "f809b7e7faacf9f60fb43486fa01b9ac83b34ef648904f27b12ffb4f74e0027d"

[[files]]
file = "mods/cc-restitched-1.100.8.jar"
hash = "8edab8d889680478279c0411b80c411cb0791f0b27cdb386f6ac5e2fd1cd718e"

[[files]]
file = "mods/clientcommands-2.6.6.jar"
hash = "93136e6d9040673dbc860e6f0f9a80951738a34089a8c32fd3a3a3b7835f25b1"

[[files]]
file = "mods/cloth-config-fabric-6.2.62.jar"
hash = "6c2cc205ececddebc6625eccbd37e3bb284acded7a67c74225894b9430f9e6d5"

[[files]]
file = "mods/dawn-3.3.2.jar"
hash = "66d2476ed2e9f8e8bf3c435c54ceadae50c9603a6c4d4331c925a6ca7a1dde34"

[[files]]
file = "mods/emotecraft-for-MC1.18.2-2.1.3-SNAPSHOT-build.32-fabric.jar"
hash = "20e5c2a434913038a05924fd7a50c072969de0e77cb360263751fd54102c256f"

[[files]]
file = "mods/enhancedblockentities-0.7.1+1.18.2.jar"
hash = "77b979605b211a85fe9b873351b9c6068a2cee131e4f30619bb3b03013517bac"

[[files]]
file = "mods/fabric-api-0.57.0+1.18.2.jar"
hash = "e0449f3017b0b77bca647cf5f2cc6292ec47b28461c2f84d53e6f461f5f906d3"

[[files]]
file = "mods/ferritecore-4.2.1-fabric.jar"
hash = "17651e8a18f88c58fa0dbcd462507899f8a0136b72da8fd7e5eb5ad95ba2260a"

[[files]]
file = "mods/forcecloseloadingscreen-1.1.1.jar"
hash = "6b2de687655ec10465884df7014cc5e4ce526cd59db5ebef51fa291b1076e72b"

[[files]]
file = "mods/half-doors-1.18.2-fabric-1.3.6.jar"
hash = "4c339d5d49ff52cb10f0b5591f5645baf7243042788e99d2c2ba3c4bcf8c9cfa"

[[files]]
file = "mods/immersive-portals-1.4.8-mc1.18.2-fabric.jar"
hash = "9ac9d238992f904d712c701d3e412aed29579f82a39641d5dcc0f4282340d7f8"

[[files]]
file = "mods/immersive_weathering-2.5.6.jar"
hash = "2f2afdcb766caa88d779cd552c652176ba1f718f380e08f256abf403a9245c25"

[[files]]
file = "mods/indium-1.0.6+mc1.18.2.jar"
hash = "6306e98b74f95c08284043d52b02b7cf0c00b147ede6f89ff715061794fa05ac"

[[files]]
file = "mods/jei-1.18.2-fabric-10.1.0.208.jar"
hash = "e4c85c262d35008834743f05d52728854d5d8d062f9774f9e7063ad29011fdfe"

[[files]]
file = "mods/kiln-1.2.0+1.18.2.jar"
hash = "bc3b5ff756677ab1225ba596d4ca481f608978930f5c2eb12c8c290cb07170b4"

[[files]]
file = "mods/lambdynamiclights-2.1.0+1.17.jar"
hash = "d17bd6e230110e399d43f86cc9c820ae8b0ff1af7fa9f9cd686aec59495c195d"

[[files]]
file = "mods/lazydfu-0.1.2.jar"
hash = "e78eb1492e20bcd8c998d4142dd437c2517393c5d02f582204ad8a38341e75e8"

[[files]]
file = "mods/litematica-fabric-1.18.2-0.11.3.jar"
hash = "379c552c8c85b0c6a0aecdea2313409cbb6f836581b56afc87c91fcc3ea08830"

[[files]]
file = "mods/lithium-fabric-mc1.18.2-0.7.10.jar"
hash = "fce2a8e9174c4b8210a73e54df6923fc84784ce4c89230cdc5dddddbf366bbbc"

[[files]]
file = "mods/logical_zoom-0.0.14.jar"
hash = "799c2eac27774835b23c1ee4e694e1c25526937bb9533113e7f397c36ed3f6d7"

[[files]]
file = "mods/lovely_snails-1.0.4+1.18.jar"
hash = "3d035a8f2132b146488fcd55c6eb17bc72470dd5ccd1bf4532a52762b788a685"

[[files]]
file = "mods/malilib-fabric-1.18.2-0.12.1.jar"
hash = "825c7c1c00b208c3999c3dc5706afbf3e1d6b8156c82f0bc5a588979dbafd3ea"

[[files]]
file = "mods/midnightlib-0.4.4.jar"
hash = "3052664292756b4da6a04efaa0dabdfc346b9f1fe30d69d577d766a1ad1efa6d"

[[files]]
file = "mods/minihud-fabric-1.18.2-0.22.0.jar"
hash = "e8c7d7c9b513f66bfd3a17c6fa93c447b7602ad81c76f2184182a0a2268fc312"

[[files]]
file = "mods/modmenu-3.2.3.jar"
hash = "e577b5403d41c7c9515ee7cf45752d3b856a6bb96d6b937760df3fad483dbc18"

[[files]]
file = "mods/rocks-1.6.0.jar"
hash = "3cd1e24a139dcf5067322f00158c940a9db80c932e7f88b3eb58136e900ff00f"

[[files]]
file = "mods/server-hats-0.9.jar"
hash = "bc2f737893787b661d43aadb87946e8df8eb812a69bd57746d630cf831bb04d3"

[[files]]
file = "mods/servertick-mc1.18-1.6.jar"
hash = "f25a74f08ae0fb041028c04f58a6a20540c87072c6a9e57a9ab8510b5d109a0c"

[[files]]
file = "mods/sodium-fabric-mc1.18.2-0.4.1+build.15.jar"
hash = "776fb3cd8c8ddee898eb1d9dc88a72d899aaa8792f21914b39ad990cea253784"

[[files]]
file = "mods/stacker-3.0.1-1.18.2.jar"
hash = "ca3c515c2f0fcde6cdd2184737f6d43fcff7716faa7ad1c8255fa9814d5930c7"

[[files]]
file = "mods/starlight-1.0.2+fabric.89b8d9f.jar"
hash = "d8a8cfdd61502f5355581be72751ee35215418cc53de23a02071ee1ee295372d"

[[files]]
file = "mods/technomodel-1.0.2.jar"
hash = "a1a80da71c99e2f4b104d92c43f8d743c680aa0274e1adad1a3911e24868a205"

[[files]]
file = "mods/traverse-5.1.0.jar"
hash = "fad506c5e724908e4f0f0a267a1e63f4e4bd18783697185cd23763ed390d83b5"

[[files]]
file = "mods/trinkets-3.3.1.jar"
hash = "985920fe4affcd9c1e998eff1a0e63ce38e8ab869f1c14376742125d65c48108"

[[files]]
file = "mods/universal_ores-1.3.0.jar"
hash = "83d20b24363b4a7281a7ce09e60506fdb62ce1da608d122ec3bc2c7138845dd1"

[[files]]
file = "mods/voicechat-fabric-1.18.2-2.2.47.jar"
hash = "3972849a431eec89620514fda363d2edff37bfae83a13d55908fe15125039731"

[[files]]
file = "mods/wthit-fabric-4.11.0.jar"
hash = "1fe3511b98c76207e478de61d66345e21c724a541765030099ff9b899e141732"
