name = "Stable Modpack"
author = "OneYellowLemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "934175c3842d7a60da7f3861bcbd69227ab85618a8e84ed051473a128d1ea628"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
