name = "Stable Modpack"
author = "OneYellowLemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90cfa80dbc97bdfa32e80ad83b13f05ba3063048ca730e72fbcddac07c98ff54"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
